name: "Omega Zirkel Planks N Beams (com.vms.PlanksAndBeams)"
main: de.omegazirkel.risingworld.PNB
version: 0.7.0-SNAPSHOT
author: "Maik 'Devidian' Laschober"
team: "Omega Zirkel"
description: "PNB Plugin, originally written by 'Maurizio M. Gavioli aka Miwarre'"
license: EMS
website: coming soon